import { Geofence } from './types'

export const GEOFENCES: Geofence[] = [

  // ── 泰国 ──
  {
    id: 'th-chiangmai',
    name: 'Chiang Mai',
    city: 'Chiang Mai',
    country: 'Thailand',
    country_code: 'TH',
    timezone: 'Asia/Bangkok',
    language: 'zh',
    lat: 18.7883,
    lng: 98.9853,
    radius_km: 50,
    currency: 'THB',
    currency_symbol: '฿',
    calling_code: '+66',
    form_types: ['TM7', 'TM47', 'TM8', 'medical_form', 'school_absence', 'driving_license'],
    local_sources: {
      news_keywords: ['Chiang Mai', '清迈', 'เชียงใหม่', 'CM108', 'Chiang Mai 108'],
      official_sites: [
        'https://www.chiangmai.go.th',
        'https://www.immigration.go.th',
        'https://cm108.com',
      ],
      patrol_prompt: '清迈本地今日情况：天气AQI、主要道路交通、移民局政策、学校通知、健康疾病预警、周边活动',
      emergency: {
        police: '191',
        ambulance: '1669',
        fire: '199',
        tourist_police: '1155',
      },
    },
  },

  {
    id: 'th-bangkok',
    name: 'Bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    country_code: 'TH',
    timezone: 'Asia/Bangkok',
    language: 'zh',
    lat: 13.7563,
    lng: 100.5018,
    radius_km: 80,
    currency: 'THB',
    currency_symbol: '฿',
    calling_code: '+66',
    form_types: ['TM7', 'TM47', 'TM8', 'medical_form', 'school_absence', 'driving_license'],
    local_sources: {
      news_keywords: ['Bangkok', '曼谷', 'กรุงเทพ', 'BTS', 'MRT Bangkok'],
      official_sites: [
        'https://www.bangkok.go.th',
        'https://www.immigration.go.th',
      ],
      patrol_prompt: '曼谷本地今日情况：天气交通（BTS/MRT）、移民局政策、空气质量、学校通知、健康预警、周边活动',
      emergency: {
        police: '191',
        ambulance: '1669',
        fire: '199',
        tourist_police: '1155',
      },
    },
  },

  {
    id: 'th-phuket',
    name: 'Phuket',
    city: 'Phuket',
    country: 'Thailand',
    country_code: 'TH',
    timezone: 'Asia/Bangkok',
    language: 'zh',
    lat: 7.8804,
    lng: 98.3923,
    radius_km: 40,
    currency: 'THB',
    currency_symbol: '฿',
    calling_code: '+66',
    form_types: ['TM7', 'TM47', 'TM8', 'medical_form', 'driving_license'],
    local_sources: {
      news_keywords: ['Phuket', '普吉', 'ภูเก็ต', 'Phuket News'],
      official_sites: [
        'https://www.phuket.go.th',
        'https://www.immigration.go.th',
      ],
      patrol_prompt: '普吉岛本地今日情况：天气海况、移民局政策、交通、健康预警、旅游活动',
      emergency: {
        police: '191',
        ambulance: '1669',
        fire: '199',
        tourist_police: '1155',
      },
    },
  },

  {
    id: 'th-pattaya',
    name: 'Pattaya',
    city: 'Pattaya',
    country: 'Thailand',
    country_code: 'TH',
    timezone: 'Asia/Bangkok',
    language: 'zh',
    lat: 12.9236,
    lng: 100.8825,
    radius_km: 30,
    currency: 'THB',
    currency_symbol: '฿',
    calling_code: '+66',
    form_types: ['TM7', 'TM47', 'TM8', 'medical_form'],
    local_sources: {
      news_keywords: ['Pattaya', '芭提雅', 'พัทยา', 'Pattaya News'],
      official_sites: ['https://www.immigration.go.th'],
      patrol_prompt: '芭提雅本地今日情况：天气、移民局政策、交通、健康预警、活动',
      emergency: {
        police: '191',
        ambulance: '1669',
        fire: '199',
        tourist_police: '1155',
      },
    },
  },

  // ── 东南亚 ──
  {
    id: 'sg-singapore',
    name: 'Singapore',
    city: 'Singapore',
    country: 'Singapore',
    country_code: 'SG',
    timezone: 'Asia/Singapore',
    language: 'zh',
    lat: 1.3521,
    lng: 103.8198,
    radius_km: 30,
    currency: 'SGD',
    currency_symbol: 'S$',
    calling_code: '+65',
    form_types: ['medical_form', 'school_absence', 'school_registration'],
    local_sources: {
      news_keywords: ['Singapore', '新加坡', 'MOM Singapore', 'MOE Singapore', 'ICA Singapore'],
      official_sites: [
        'https://www.ica.gov.sg',
        'https://www.mom.gov.sg',
        'https://www.moe.gov.sg',
      ],
      patrol_prompt: '新加坡今日情况：天气、MRT交通、移民局ICA政策更新、教育部MOE通知、健康预警、活动',
      emergency: {
        police: '999',
        ambulance: '995',
        fire: '995',
      },
    },
  },

  {
    id: 'my-kualalumpur',
    name: 'Kuala Lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    country_code: 'MY',
    timezone: 'Asia/Kuala_Lumpur',
    language: 'zh',
    lat: 3.1390,
    lng: 101.6869,
    radius_km: 50,
    currency: 'MYR',
    currency_symbol: 'RM',
    calling_code: '+60',
    form_types: ['medical_form', 'school_absence'],
    local_sources: {
      news_keywords: ['Kuala Lumpur', '吉隆坡', 'KL', 'Malaysia immigration', 'MOE Malaysia'],
      official_sites: [
        'https://www.imi.gov.my',
        'https://www.moe.gov.my',
      ],
      patrol_prompt: '吉隆坡今日情况：天气、交通（LRT/MRT）、移民局政策、教育通知、健康预警、活动',
      emergency: {
        police: '999',
        ambulance: '999',
        fire: '994',
      },
    },
  },

  {
    id: 'id-bali',
    name: 'Bali',
    city: 'Bali',
    country: 'Indonesia',
    country_code: 'ID',
    timezone: 'Asia/Makassar',
    language: 'zh',
    lat: -8.3405,
    lng: 115.0920,
    radius_km: 60,
    currency: 'IDR',
    currency_symbol: 'Rp',
    calling_code: '+62',
    form_types: ['medical_form'],
    local_sources: {
      news_keywords: ['Bali', '巴厘岛', 'Bali immigration', 'KITAS', 'Bali expat'],
      official_sites: ['https://www.imigrasi.go.id'],
      patrol_prompt: '巴厘岛今日情况：天气、火山活动、移民局KITAS政策、交通、健康预警、活动',
      emergency: {
        police: '110',
        ambulance: '118',
        fire: '113',
      },
    },
  },

  {
    id: 'ph-manila',
    name: 'Manila',
    city: 'Manila',
    country: 'Philippines',
    country_code: 'PH',
    timezone: 'Asia/Manila',
    language: 'zh',
    lat: 14.5995,
    lng: 120.9842,
    radius_km: 50,
    currency: 'PHP',
    currency_symbol: '₱',
    calling_code: '+63',
    form_types: ['medical_form', 'school_absence'],
    local_sources: {
      news_keywords: ['Manila', '马尼拉', 'Philippines immigration', 'BI Philippines'],
      official_sites: ['https://www.immigration.gov.ph'],
      patrol_prompt: '马尼拉今日情况：天气台风、交通、移民局政策、健康预警、活动',
      emergency: {
        police: '117',
        ambulance: '911',
        fire: '911',
      },
    },
  },

  // ── 欧洲 ──
  {
    id: 'pt-lisbon',
    name: 'Lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    country_code: 'PT',
    timezone: 'Europe/Lisbon',
    language: 'zh',
    lat: 38.7223,
    lng: -9.1393,
    radius_km: 40,
    currency: 'EUR',
    currency_symbol: '€',
    calling_code: '+351',
    form_types: ['medical_form', 'school_absence', 'bank_account'],
    local_sources: {
      news_keywords: ['Lisbon', '里斯本', 'Portugal NHR', 'SEF Portugal', 'AIMA Portugal'],
      official_sites: [
        'https://www.aima.gov.pt',
        'https://www.portaldasfinancas.gov.pt',
      ],
      patrol_prompt: '里斯本今日情况：天气、移民局AIMA政策、NHR税务、交通、学校通知、健康预警',
      emergency: {
        police: '112',
        ambulance: '112',
        fire: '112',
      },
    },
  },

  {
    id: 'es-barcelona',
    name: 'Barcelona',
    city: 'Barcelona',
    country: 'Spain',
    country_code: 'ES',
    timezone: 'Europe/Madrid',
    language: 'zh',
    lat: 41.3851,
    lng: 2.1734,
    radius_km: 40,
    currency: 'EUR',
    currency_symbol: '€',
    calling_code: '+34',
    form_types: ['medical_form', 'school_absence', 'bank_account'],
    local_sources: {
      news_keywords: ['Barcelona', '巴塞罗那', 'Spain visa', 'NIE Spain', 'Barcelona expat'],
      official_sites: ['https://www.exteriores.gob.es'],
      patrol_prompt: '巴塞罗那今日情况：天气、移民局NIE签证政策、交通、学校通知、健康预警',
      emergency: {
        police: '112',
        ambulance: '112',
        fire: '112',
      },
    },
  },

  {
    id: 'de-berlin',
    name: 'Berlin',
    city: 'Berlin',
    country: 'Germany',
    country_code: 'DE',
    timezone: 'Europe/Berlin',
    language: 'zh',
    lat: 52.5200,
    lng: 13.4050,
    radius_km: 50,
    currency: 'EUR',
    currency_symbol: '€',
    calling_code: '+49',
    form_types: ['medical_form', 'school_absence', 'bank_account'],
    local_sources: {
      news_keywords: ['Berlin', '柏林', 'Ausländerbehörde Berlin', 'Germany visa', 'Berlin expat'],
      official_sites: ['https://www.berlin.de/labo/willkommen-in-berlin/'],
      patrol_prompt: '柏林今日情况：天气、外管局Ausländerbehörde政策、交通、学校通知、健康预警',
      emergency: {
        police: '110',
        ambulance: '112',
        fire: '112',
      },
    },
  },

  {
    id: 'nl-amsterdam',
    name: 'Amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    country_code: 'NL',
    timezone: 'Europe/Amsterdam',
    language: 'zh',
    lat: 52.3676,
    lng: 4.9041,
    radius_km: 40,
    currency: 'EUR',
    currency_symbol: '€',
    calling_code: '+31',
    form_types: ['medical_form', 'school_absence', 'bank_account'],
    local_sources: {
      news_keywords: ['Amsterdam', '阿姆斯特丹', 'IND Netherlands', 'Dutch visa', 'Amsterdam expat'],
      official_sites: ['https://www.ind.nl'],
      patrol_prompt: '阿姆斯特丹今日情况：天气、IND移民政策、交通、学校通知、健康预警',
      emergency: {
        police: '112',
        ambulance: '112',
        fire: '112',
      },
    },
  },

  // ── 北美 ──
  {
    id: 'ca-vancouver',
    name: 'Vancouver',
    city: 'Vancouver',
    country: 'Canada',
    country_code: 'CA',
    timezone: 'America/Vancouver',
    language: 'zh',
    lat: 49.2827,
    lng: -123.1207,
    radius_km: 50,
    currency: 'CAD',
    currency_symbol: 'C$',
    calling_code: '+1',
    form_types: ['medical_form', 'school_absence', 'bank_account'],
    local_sources: {
      news_keywords: ['Vancouver', '温哥华', 'IRCC Canada', 'BC immigration', 'Vancouver school'],
      official_sites: [
        'https://www.canada.ca/en/immigration-refugees-citizenship.html',
        'https://www2.gov.bc.ca',
      ],
      patrol_prompt: '温哥华今日情况：天气、IRCC移民政策、BC省教育通知、交通、健康预警',
      emergency: {
        police: '911',
        ambulance: '911',
        fire: '911',
      },
    },
  },

  {
    id: 'us-losangeles',
    name: 'Los Angeles',
    city: 'Los Angeles',
    country: 'United States',
    country_code: 'US',
    timezone: 'America/Los_Angeles',
    language: 'zh',
    lat: 34.0522,
    lng: -118.2437,
    radius_km: 60,
    currency: 'USD',
    currency_symbol: '$',
    calling_code: '+1',
    form_types: ['medical_form', 'school_absence', 'bank_account'],
    local_sources: {
      news_keywords: ['Los Angeles', '洛杉矶', 'USCIS', 'LA school district', 'California DMV'],
      official_sites: [
        'https://www.uscis.gov',
        'https://www.lausd.net',
      ],
      patrol_prompt: '洛杉矶今日情况：天气、USCIS移民政策、LAUSD学校通知、交通、健康预警',
      emergency: {
        police: '911',
        ambulance: '911',
        fire: '911',
      },
    },
  },

  // ── 香港 ──
  {
    id: 'hk-hongkong',
    name: 'Hong Kong',
    city: 'Hong Kong',
    country: 'Hong Kong',
    country_code: 'HK',
    timezone: 'Asia/Hong_Kong',
    language: 'zh',
    lat: 22.3193,
    lng: 114.1694,
    radius_km: 30,
    currency: 'HKD',
    currency_symbol: 'HK$',
    calling_code: '+852',
    form_types: ['medical_form', 'school_absence', 'bank_account'],
    local_sources: {
      news_keywords: ['Hong Kong', '香港', 'Immigration HK', 'HKID', 'DSE Hong Kong'],
      official_sites: [
        'https://www.immd.gov.hk',
        'https://www.edb.gov.hk',
      ],
      patrol_prompt: '香港今日情况：天气台风、MTR交通、入境处政策、教育局通知、健康预警',
      emergency: {
        police: '999',
        ambulance: '999',
        fire: '999',
      },
    },
  },
]

// 通用全球模板（没有匹配围栏时使用）
export const DEFAULT_GEOFENCE: Geofence = {
  id: 'global-default',
  name: 'Global',
  city: 'Unknown',
  country: 'Unknown',
  country_code: 'XX',
  timezone: 'UTC',
  language: 'zh',
  lat: 0,
  lng: 0,
  radius_km: 99999,
  currency: 'USD',
  currency_symbol: '$',
  calling_code: '+1',
  form_types: ['medical_form'],
  local_sources: {
    news_keywords: ['expat family', '海外华人家庭', 'international school'],
    official_sites: [],
    patrol_prompt: '全球华人陪读家庭关注信息：汇率、国际学校动态、海外华人社区、健康预警',
    emergency: {
      police: '当地报警电话',
      ambulance: '当地急救电话',
      fire: '当地消防电话',
    },
  },
}
